# Generated by Django 4.0.5 on 2022-06-28 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('subject', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('date_enter', models.DateTimeField(null=True)),
                ('function', models.CharField(max_length=100, null=True)),
                ('subject', models.CharField(max_length=500, null=True)),
                ('serial_num', models.IntegerField(null=True)),
                ('type_user', models.CharField(choices=[('تک کاربر', 'تک کاربر'), ('کاربر گروهی', 'کاربر گروهی')], max_length=30, null=True)),
                ('error', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nameprocess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('subject', models.CharField(max_length=500, null=True)),
                ('timeprocess', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100, null=True)),
                ('l_name', models.CharField(max_length=100, null=True)),
                ('date_enter', models.DateTimeField(null=True)),
                ('education', models.CharField(max_length=200, null=True)),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=30, null=True)),
                ('mobile', models.CharField(max_length=100, null=True)),
                ('salary', models.FloatField(max_length=100, null=True)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.job')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=200, null=True)),
                ('category', models.CharField(choices=[('قاشق', 'قاشق'), ('چنگال', 'چنگال')], max_length=50, null=True)),
                ('max_in_box', models.IntegerField(null=True)),
                ('pirce', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in process', 'در حال تولید'), ('complete', 'کامل'), ('defective', 'معیوب')], max_length=50, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('number', models.IntegerField(null=True)),
                ('Product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.product')),
                ('machine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.machine')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.nameprocess')),
                ('personal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.personal')),
            ],
        ),
    ]
