# Generated by Django 4.0.2 on 2022-06-15 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_user_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('فاشق', 'قاشق'), ('fork', 'چنگال')], max_length=50, null=True),
        ),
    ]
