# Generated by Django 4.0.2 on 2022-06-15 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('قاشق', 'قاشق'), ('چنگال', 'چنگال')], max_length=50, null=True),
        ),
    ]
