# Generated by Django 4.0.2 on 2022-06-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_user_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='type_user',
            field=models.CharField(choices=[('تک کاربر', 'تک کاربر'), ('کاربر گروهی', 'کاربر گروهی')], max_length=30, null=True),
        ),
    ]
