# Generated by Django 4.0.2 on 2022-06-21 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_alter_process_name_delete_nameprocess'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nameprocess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('subject', models.CharField(max_length=500, null=True)),
                ('timeprocess', models.FloatField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='process',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.nameprocess'),
        ),
    ]
