# Generated by Django 4.0.2 on 2022-06-21 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_nameprocess_alter_process_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.nameprocess'),
        ),
    ]
