# Generated by Django 4.0.2 on 2022-06-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_alter_process_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nameprocess',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
